// Generated by gencpp from file yumi_hw/YumiGraspResponse.msg
// DO NOT EDIT!


#ifndef YUMI_HW_MESSAGE_YUMIGRASPRESPONSE_H
#define YUMI_HW_MESSAGE_YUMIGRASPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yumi_hw
{
template <class ContainerAllocator>
struct YumiGraspResponse_
{
  typedef YumiGraspResponse_<ContainerAllocator> Type;

  YumiGraspResponse_()
    {
    }
  YumiGraspResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> const> ConstPtr;

}; // struct YumiGraspResponse_

typedef ::yumi_hw::YumiGraspResponse_<std::allocator<void> > YumiGraspResponse;

typedef boost::shared_ptr< ::yumi_hw::YumiGraspResponse > YumiGraspResponsePtr;
typedef boost::shared_ptr< ::yumi_hw::YumiGraspResponse const> YumiGraspResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yumi_hw::YumiGraspResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace yumi_hw

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::yumi_hw::YumiGraspResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yumi_hw/YumiGraspResponse";
  }

  static const char* value(const ::yumi_hw::YumiGraspResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::yumi_hw::YumiGraspResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YumiGraspResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yumi_hw::YumiGraspResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::yumi_hw::YumiGraspResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // YUMI_HW_MESSAGE_YUMIGRASPRESPONSE_H
